### ISSUE TITLE
Add default value for media migration so that stub creator can add media item stubs.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1954]
## Problem/Motivation
If a content editor deletes media on the source site for a migration, but does not delete the reference to that media the migration fails during the `migration_lookup` process referencing az_media.

### Describe the bug
az_media doesn't have a default media bundle set.

**Comment by trackleft** [comment]
Alternatively we can add no_stub: true to all migration_lookup processes that reference az_media

**Comment by trackleft** [comment]
Error 
```[error]  Error: Call to a member function getSource() on null in Drupal\media\Entity\Media->getSource() (line 137 of /app/web/core/modules/media/src/Entity/Media.php) #0 /app/web/core/modules/media/src/Entity/Media.php(371): Drupal\media\Entity\Media->getSource()
#1 /app/web/core/modules/media/src/MediaStorage.php(27): Drupal\media\Entity\Media->prepareSave()
#2 /app/web/core/lib/Drupal/Core/Entity/EntityBase.php(339): Drupal\media\MediaStorage->save(Object(Drupal\media\Entity\Media))
#3 /app/web/core/modules/migrate/src/Plugin/migrate/destination/EntityContentBase.php(248): Drupal\Core\Entity\EntityBase->save()
#4 /app/web/core/modules/migrate/src/Plugin/migrate/destination/EntityContentBase.php(186): Drupal\migrate\Plugin\migrate\destination\EntityContentBase->save(Object(Drupal\media\Entity\Media), Array)
#5 /app/web/core/modules/migrate/src/MigrateStub.php(118): Drupal\migrate\Plugin\migrate\destination\EntityContentBase->import(Object(Drupal\migrate\Row))
#6 /app/web/core/modules/migrate/src/MigrateStub.php(80): Drupal\migrate\MigrateStub->doCreateStub(Object(Drupal\migrate\Plugin\Migration), Array, Array)
#7 /app/web/core/modules/migrate/src/Plugin/migrate/process/MigrationLookup.php(250): Drupal\migrate\MigrateStub->createStub('az_media', Array, Array, false)
#8 /app/web/core/modules/migrate/src/MigrateExecutable.php(448): Drupal\migrate\Plugin\migrate\process\MigrationLookup->transform('167', Object(Drupal\migrate_tools\MigrateExecutable), Object(Drupal\migrate\Row), 'target_id')
#9 /app/web/core/modules/migrate/src/MigrateExecutable.php(392): Drupal\migrate\MigrateExecutable->processPipeline(Object(Drupal\migrate\Row), 'target_id', Array, '167')
#10 /app/web/core/modules/migrate/src/Plugin/migrate/process/SubProcess.php(211): Drupal\migrate\MigrateExecutable->processRow(Object(Drupal\migrate\Row), Array)
#11 /app/web/core/modules/migrate/src/MigrateExecutable.php(448): Drupal\migrate\Plugin\migrate\process\SubProcess->transform(Array, Object(Drupal\migrate_tools\MigrateExecutable), Object(Drupal\migrate\Row), 'field_az_media')
#12 /app/web/core/modules/migrate/src/MigrateExecutable.php(221): Drupal\migrate\MigrateExecutable->processPipeline(Object(Drupal\migrate\Row), 'field_az_media', Array, Array)
#13 /app/vendor/drush/drush/includes/drush.inc(122): Drupal\migrate\MigrateExecutable->import()
#14 /app/vendor/drush/drush/includes/drush.inc(113): drush_call_user_func_array(Array, Array)
#15 /app/web/modules/contrib/migrate_tools/src/Commands/MigrateToolsCommands.php(963): drush_op(Array)
#16 [internal function]: Drupal\migrate_tools\Commands\MigrateToolsCommands->executeMigration(Object(Drupal\migrate\Plugin\Migration), 'az_paragraph_fu...', Array)
#17 /app/web/modules/contrib/migrate_tools/src/Commands/MigrateToolsCommands.php(417): array_walk(Array, Array, Array)
#18 [internal function]: Drupal\migrate_tools\Commands\MigrateToolsCommands->import('', Array)
#19 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#20 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#21 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#22 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#23 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /app/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /app/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#30 /app/vendor/drush/drush/drush(3): require('/app/vendor/dru...')
#31 /app/vendor/bin/drush(112): include('/app/vendor/dru...')
#32 {main}. 
```
