### ISSUE TITLE
Text Area  paragraphs behavior settings migrating incorrectly.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2277]
## Problem/Motivation
I was seeing an error in the log for a migrated site.

```
Warning: Array to string conversion in Drupal\Core\Template\AttributeArray->__toString() (line 77 of /code/web/core/lib/Drupal/Core/Template/AttributeArray.php)
#0 /code/web/core/includes/bootstrap.inc(347): _drupal_error_handler_real(2, 'Array to string...', '/code/web/core/...', 77)
#1 [internal function]: _drupal_error_handler(2, 'Array to string...', '/code/web/core/...', 77)
#2 /code/web/core/lib/Drupal/Core/Template/AttributeArray.php(77): array_unique(Array)
#3 /code/web/core/lib/Drupal/Core/Template/AttributeValueBase.php(53): Drupal\Core\Template\AttributeArray->__toString()
#4 /code/web/core/lib/Drupal/Core/Template/Attribute.php(324): Drupal\Core\Template\AttributeValueBase->render()
#5 /tmp/rolling/live_10/twig/6405dbb938a02_paragraph.html.twig_af0b05djb-ThITky-XalN2WmZ/s5eTGAp0im32-YA4VtunZtmKGtl9gxym3au_ge6pGHc.php(54): Drupal\Core\Template\Attribute->__toString()
#6 /code/vendor/twig/twig/src/Template.php(182): __TwigTemplate_f60b6cb8543e44cd56c94d6fa84667d2d2875583cff599173ef9d1ddba990017->block_paragraph(Array, Array)
#7 /tmp/rolling/live_10/twig/6405dbb938a02_paragraph.html.twig_af0b05djb-ThITky-XalN2WmZ/s5eTGAp0im32-YA4VtunZtmKGtl9gxym3au_ge6pGHc.php(46): Twig\Template->displayBlock('paragraph', Array, Array)
#8 /code/vendor/twig/twig/src/Template.php(405): __TwigTemplate_f60b6cb8543e44cd56c94d6fa84667d2d2875583cff599173ef9d1ddba990017->doDisplay(Array, Array)
#9 /code/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /code/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#11 /code/web/core/themes/engines/twig/twig.engine(55): Twig\Template->render(Array)
#12 /code/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('modules/contrib...', Array)
#13 /code/web/core/lib/Drupal/Core/Render/Renderer.php(433): Drupal\Core\Theme\ThemeManager->render('paragraph', Array)
#14 /code/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#15 /code/web/core/lib/Drupal/Core/Template/TwigExtension.php(479): Drupal\Core\Render\Renderer->render(Array)
#16 /tmp/rolling/live_10/twig/6405dbb938a02_field.html.twig_AnB4Qi-CILtBxGi9RniqPI3Yf/oElAcbJRHMBC8HYrRxLwrUHRv82JWefjCgWMTDeBNTk.php(70): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#17 /code/vendor/twig/twig/src/Template.php(405): __TwigTemplate_7c15e0508bc6e6f900ab13459e87dcfd13259eb982360a9b0421fc6624c5f19b->doDisplay(Array, Array)
#18 /code/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /code/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#20 /code/web/core/themes/engines/twig/twig.engine(55): Twig\Template->render(Array)
#21 /code/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/custom...', Array)
#22 /code/web/core/lib/Drupal/Core/Render/Renderer.php(433): Drupal\Core\Theme\ThemeManager->render('field', Array)
#23 /code/web/core/lib/Drupal/Core/Render/Renderer.php(446): Drupal\Core\Render\Renderer->doRender(Array)
#24 /code/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#25 /code/web/core/lib/Drupal/Core/Template/TwigExtension.php(479): Drupal\Core\Render\Renderer->render(Array)
#26 /tmp/rolling/live_10/twig/6405dbb938a02_node.html.twig_yNAD_vNAmNQ4Z2FodlEfW2XJN/J7pqKyz8IeTx38tRsfkkvbMMBUiFJwldcpDtW9gIEpA.php(107): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#27 /code/vendor/twig/twig/src/Template.php(405): __TwigTemplate_5ae0dc29d679467e12bf88e918774b7adf8b458b99b7e07c622d9b453f37d45a->doDisplay(Array, Array)
#28 /code/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /code/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#30 /code/web/core/themes/engines/twig/twig.engine(55): Twig\Template->render(Array)
#31 /code/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('themes/contrib/...', Array)
#32 /code/web/core/lib/Drupal/Core/Render/Renderer.php(433): Drupal\Core\Theme\ThemeManager->render('node', Array)
#33 /code/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#34 /code/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(242): Drupal\Core\Render\Renderer->render(Array, false)
#35 /code/web/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#36 /code/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(243): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#37 /code/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(132): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#38 /code/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#39 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#40 /code/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#41 /code/vendor/symfony/http-kernel/HttpKernel.php(174): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view')
#42 /code/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#43 /code/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#44 /code/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#45 /code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#46 /code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#47 /code/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#48 /code/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#49 /code/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#50 /code/web/core/lib/Drupal/Core/DrupalKernel.php(713): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#51 /code/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#52 {main}
.
```

It manifests itself on the front end as `Array` within the class list of text paragraphs.

![image](https://user-images.githubusercontent.com/1023167/223194184-6855bb81-7199-4755-a73d-84942754c0a2.png)

During the investigation, I found that resaving the content with the afflicted paragraph attached resolved the issue.

After confirming that resaving the paragraphs that were triggering the error, I looked in the database to see what was going on.

In the database table `paragraphs_item_field_data` I saw the following in the `behavior_settings` field
```
a:1:{s:29:"az_default_paragraph_behavior";a:1:{s:19:"az_display_settings";a:1:{s:14:"bottom_spacing";a:1:{i:0;a:2:{s:6:"plugin";N;s:13:"default_value";N;}}}}}
```
Unserialized, looks like this
```
Array
(
    [az_default_paragraph_behavior] => Array
        (
            [az_display_settings] => Array
                (
                    [bottom_spacing] => Array
                        (
                            [0] => Array
                                (
                                    [plugin] => 
                                    [default_value] => 
                                )

                        )

                )

        )

)
```
Paragraphs that actually work, should look like this
```
a:1:{s:29:"az_default_paragraph_behavior";a:1:{s:19:"az_display_settings";a:1:{s:14:"bottom_spacing";s:4:"mb-0";}}}
```
Or unserialized
```
Array
(
    [az_default_paragraph_behavior] => Array
        (
            [az_display_settings] => Array
                (
                    [bottom_spacing] => mb-0
                )

        )

)

```
After that, I went and checked out our migration for `az_headed_text` and found this https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/migrations/az_paragraph_headed_text.yml#L32-L39
```

  behavior_settings:
    plugin: az_paragraphs_behavior_settings
    paragraph_behavior_plugins:
      az_default_paragraph_behavior:
        az_display_settings:
          bottom_spacing:
            - plugin: default_value
              default_value: mb-0
```
The key here is the plugin being used to migrate paragraph behavior settings
`az_paragraphs_behavior_settings` which can be found here: https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php

With the key parts being
```
  /**
   * {@inheritdoc}
   */
  public function transform($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property): string {
    $behaviors = array_keys($this->behaviorPluginManager->getDefinitions());
    foreach ($this->configuration['paragraph_behavior_plugins'] as $behavior_id => $settings) {
      if (!$behaviors || !in_array($behavior_id, $behaviors)) {
        throw new PluginNotFoundException($behavior_id);
      }
    }

    $behavior = $this->buildSettingsArray($this->configuration['paragraph_behavior_plugins'], $row);
    $value['behavior'] = serialize($behavior);
    return $value['behavior'];
  }


  /**
   * Recursive array builder that reads values in deeply nested arrays.
   *
   * @param array $settings
   *   The behavior settings array.
   * @param \Drupal\migrate\Row $row
   *   The current row.
   *
   * @return array
   *   The behavior settings array.
   */
  protected function buildSettingsArray(array &$settings, Row $row): array {
    $branch = [];

    foreach ($settings as $key => $value) {
      if (is_array($value)) {
        $branch[$key] = $this->buildSettingsArray($value, $row);
      }
      else {
        $branch[$key] = $row->get($value);
      }
    }
    return $branch;
  }

```

**Comment by trackleft** [comment]
At the moment, it is unclear if this is a new issue as of 2.6.0 or an existing issue with 2.5.x

**Comment by trackleft** [comment]
Thanks @jfallen19  I am about to make a PR for this

**Comment by trackleft** [comment]
@jfallen19 for the Text On Media  migrations, I am not seeing data corruption issue, but you did mention something about setting the default to `aspect_ratio` is that something you can elaborate on here, or should I open a new ticket for that.
