### ISSUE TITLE
Deprecation warnings while news feed is importing

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#2852]
## Problem/Motivation
While testing 2.8.0-beta2, I noticed that some deprecation warnings are being logged when the AZ News Feeds migration is imported.

### Describe the bug
```
Deprecated function: addcslashes(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\Core\Database\Connection->escapeLike() (line 1294 of /code/web/core/lib/Drupal/Core/Database/Connection.php)
#0 /code/web/core/includes/bootstrap.inc(164): _drupal_error_handler_real(8192, 'addcslashes(): ...', '/code/web/core/...', 1294)
#1 [internal function]: _drupal_error_handler(8192, 'addcslashes(): ...', '/code/web/core/...', 1294)
#2 /code/web/core/lib/Drupal/Core/Database/Connection.php(1294): addcslashes(NULL, '\\%_')
#3 /code/web/core/lib/Drupal/Core/Database/Query/Select.php(431): Drupal\Core\Database\Connection->escapeLike(NULL)
#4 /code/web/core/lib/Drupal/Core/Entity/Query/Sql/Condition.php(125): Drupal\Core\Database\Query\Select->escapeLike(NULL)
#5 /code/web/core/lib/Drupal/Core/Entity/Query/Sql/Condition.php(70): Drupal\Core\Entity\Query\Sql\Condition::translateCondition(Array, Object(Drupal\mysql\Driver\Database\mysql\Select), false)
#6 /code/web/core/lib/Drupal/Core/Entity/Query/Sql/Query.php(176): Drupal\Core\Entity\Query\Sql\Condition->compile(Object(Drupal\mysql\Driver\Database\mysql\Select))
#7 /code/web/core/lib/Drupal/Core/Entity/Query/Sql/Query.php(81): Drupal\Core\Entity\Query\Sql\Query->compile()
#8 /code/web/modules/contrib/migrate_plus/src/Plugin/migrate/process/EntityLookup.php(256): Drupal\Core\Entity\Query\Sql\Query->execute()
#9 /code/web/modules/contrib/migrate_plus/src/Plugin/migrate/process/EntityLookup.php(141): Drupal\migrate_plus\Plugin\migrate\process\EntityLookup->query(NULL)
#10 /code/web/modules/contrib/migrate_plus/src/Plugin/migrate/process/EntityGenerate.php(75): Drupal\migrate_plus\Plugin\migrate\process\EntityLookup->transform(NULL, Object(Drupal\migrate_tools\MigrateExecutable), Object(Drupal\migrate\Row), 'field_az_news_t...')
#11 /code/web/core/modules/migrate/src/MigrateExecutable.php(428): Drupal\migrate_plus\Plugin\migrate\process\EntityGenerate->transform(NULL, Object(Drupal\migrate_tools\MigrateExecutable), Object(Drupal\migrate\Row), 'field_az_news_t...')
#12 /code/web/core/modules/migrate/src/MigrateExecutable.php(220): Drupal\migrate\MigrateExecutable->processPipeline(Object(Drupal\migrate\Row), 'field_az_news_t...', Array, Array)
#13 /code/web/modules/contrib/migrate_queue_importer/src/Plugin/QueueWorker/MigrateImportQueueWorker.php(104): Drupal\migrate\MigrateExecutable->import()
#14 /code/web/core/lib/Drupal/Core/Cron.php(268): Drupal\migrate_queue_importer\Plugin\QueueWorker\MigrateImportQueueWorker->processItem(Array)
#15 /code/web/core/lib/Drupal/Core/Cron.php(233): Drupal\Core\Cron->processQueue(Object(Drupal\Core\Queue\DatabaseQueue), Object(Drupal\migrate_queue_importer\Plugin\QueueWorker\MigrateImportQueueWorker))
#16 /code/web/core/lib/Drupal/Core/Cron.php(162): Drupal\Core\Cron->processQueues()
#17 /code/web/core/lib/Drupal/Core/ProxyClass/Cron.php(75): Drupal\Core\Cron->run()
#18 /code/web/core/modules/automated_cron/src/EventSubscriber/AutomatedCron.php(65): Drupal\Core\ProxyClass\Cron->run()
#19 [internal function]: Drupal\automated_cron\EventSubscriber\AutomatedCron->onTerminate(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#20 /code/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#21 /code/vendor/symfony/http-kernel/HttpKernel.php(116): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...')
#22 /code/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(63): Symfony\Component\HttpKernel\HttpKernel->terminate(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\LocalRedirectResponse))
#23 /code/web/core/lib/Drupal/Core/DrupalKernel.php(688): Drupal\Core\StackMiddleware\StackedHttpKernel->terminate(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\LocalRedirectResponse))
#24 /code/web/index.php(22): Drupal\Core\DrupalKernel->terminate(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\LocalRedirectResponse))
#25 {main}
.
```

### Expected behavior

No deprecation warnings.

**Comment by joeparsons** [comment]
This Migrate Plus contrib module issue looks related:
https://www.drupal.org/project/migrate_plus/issues/2830058
