### ISSUE TITLE
Intelligence Bank module PHP warnings

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#3637]
_Originally posted by @bberndt-uaz in https://github.com/az-digital/az_quickstart/pull/3621#pullrequestreview-2233948945_:

>Approved, but I see these warnings in the log in Probo: I believe they are an existing issue.
>
><img width="967" alt="image" src="https://github.com/user-attachments/assets/78fd6f8d-d3e1-4388-af23-8f349e56fe8e">

Confirmed that this issue existed prior to the dependabot update.

**Comment by trackleft** [comment]
Those look like schema errors

**Comment by joeparsons** [comment]
Actual warning messages:
```
Warning: Undefined array key "field_name" in Drupal\ib_dam_media\Form\MediaLibraryIbDamBrowserForm->buildForm() (line 194 of /src/az-quickstart-scaffolding/web/modules/contrib/intelligencebank/modules/ib_dam_media/src/Form/MediaLibraryIbDamBrowserForm.php)
#0 /src/az-quickstart-scaffolding/web/core/includes/bootstrap.inc(166): _drupal_error_handler_real()
#1 /src/az-quickstart-scaffolding/web/modules/contrib/intelligencebank/modules/ib_dam_media/src/Form/MediaLibraryIbDamBrowserForm.php(194): _drupal_error_handler()
#2 [internal function]: Drupal\ib_dam_media\Form\MediaLibraryIbDamBrowserForm->buildForm()
#3 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormBuilder.php(536): call_user_func_array()
#4 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormBuilder.php(284): Drupal\Core\Form\FormBuilder->retrieveForm()
#5 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm()
#6 [internal function]: Drupal\Core\Controller\FormController->getContentResult()
#7 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#8 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(638): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#9 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(121): Drupal\Core\Render\Renderer->executeInRenderContext()
#10 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#11 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#12 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#13 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/Session.php(53): Symfony\Component\HttpKernel\HttpKernel->handle()
#14 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#15 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#16 /src/az-quickstart-scaffolding/web/core/modules/big_pipe/src/StackMiddleware/ContentLength.php(32): Drupal\Core\StackMiddleware\ContentLength->handle()
#17 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\big_pipe\StackMiddleware\ContentLength->handle()
#18 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#19 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#20 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#21 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#22 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle()
#23 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/DrupalKernel.php(741): Drupal\Core\StackMiddleware\StackedHttpKernel->handle()
#24 /src/az-quickstart-scaffolding/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#25 {main}
```
```
Warning: Undefined array key "entity_type_id" in Drupal\ib_dam_media\Form\MediaLibraryIbDamBrowserForm->buildForm() (line 195 of /src/az-quickstart-scaffolding/web/modules/contrib/intelligencebank/modules/ib_dam_media/src/Form/MediaLibraryIbDamBrowserForm.php)
#0 /src/az-quickstart-scaffolding/web/core/includes/bootstrap.inc(166): _drupal_error_handler_real()
#1 /src/az-quickstart-scaffolding/web/modules/contrib/intelligencebank/modules/ib_dam_media/src/Form/MediaLibraryIbDamBrowserForm.php(195): _drupal_error_handler()
#2 [internal function]: Drupal\ib_dam_media\Form\MediaLibraryIbDamBrowserForm->buildForm()
#3 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormBuilder.php(536): call_user_func_array()
#4 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormBuilder.php(284): Drupal\Core\Form\FormBuilder->retrieveForm()
#5 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm()
#6 [internal function]: Drupal\Core\Controller\FormController->getContentResult()
#7 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#8 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(638): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#9 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(121): Drupal\Core\Render\Renderer->executeInRenderContext()
#10 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#11 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#12 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#13 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/Session.php(53): Symfony\Component\HttpKernel\HttpKernel->handle()
#14 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#15 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#16 /src/az-quickstart-scaffolding/web/core/modules/big_pipe/src/StackMiddleware/ContentLength.php(32): Drupal\Core\StackMiddleware\ContentLength->handle()
#17 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\big_pipe\StackMiddleware\ContentLength->handle()
#18 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#19 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#20 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#21 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#22 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle()
#23 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/DrupalKernel.php(741): Drupal\Core\StackMiddleware\StackedHttpKernel->handle()
#24 /src/az-quickstart-scaffolding/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#25 {main}
```
```
Warning: Undefined array key "bundle" in Drupal\ib_dam_media\Form\MediaLibraryIbDamBrowserForm->buildForm() (line 196 of /src/az-quickstart-scaffolding/web/modules/contrib/intelligencebank/modules/ib_dam_media/src/Form/MediaLibraryIbDamBrowserForm.php)
#0 /src/az-quickstart-scaffolding/web/core/includes/bootstrap.inc(166): _drupal_error_handler_real()
#1 /src/az-quickstart-scaffolding/web/modules/contrib/intelligencebank/modules/ib_dam_media/src/Form/MediaLibraryIbDamBrowserForm.php(196): _drupal_error_handler()
#2 [internal function]: Drupal\ib_dam_media\Form\MediaLibraryIbDamBrowserForm->buildForm()
#3 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormBuilder.php(536): call_user_func_array()
#4 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormBuilder.php(284): Drupal\Core\Form\FormBuilder->retrieveForm()
#5 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm()
#6 [internal function]: Drupal\Core\Controller\FormController->getContentResult()
#7 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#8 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(638): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#9 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(121): Drupal\Core\Render\Renderer->executeInRenderContext()
#10 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#11 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#12 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#13 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/Session.php(53): Symfony\Component\HttpKernel\HttpKernel->handle()
#14 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#15 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#16 /src/az-quickstart-scaffolding/web/core/modules/big_pipe/src/StackMiddleware/ContentLength.php(32): Drupal\Core\StackMiddleware\ContentLength->handle()
#17 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\big_pipe\StackMiddleware\ContentLength->handle()
#18 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#19 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#20 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#21 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#22 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle()
#23 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/DrupalKernel.php(741): Drupal\Core\StackMiddleware\StackedHttpKernel->handle()
#24 /src/az-quickstart-scaffolding/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#25 {main}
```

**Comment by joeparsons** [comment]
Created issue & MR on Drupal.org:
https://www.drupal.org/project/intelligencebank/issues/3468426
